apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: hello-tkeel-oauth2-client
  namespace: "keel-system"
spec:
  type: middleware.http.oauth2clientcredentials
  version: v1
  metadata:
  - name: clientId
    value: "hello-tkeel"
  - name: clientSecret
    value: "changeme"
  - name: scopes
    value: "http://hello-tkeel.com"
  - name: tokenURL
    value: "http://plugins:8080/oauth2/token"
  - name: headerName
    value: "x-plugin-jwt"
  - name: authStyle
    value: 1