apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tkeel
  namespace: "keel-system"
  labels:
    app: hello-tkeel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-tkeel
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "hello-tkeel"
        dapr.io/config: hello-tkeel
        dapr.io/app-port: "8080"
      labels:
        app: hello-tkeel
    spec:
      containers:
        - name: hello-tkeel
          image: tkeelio/hello-tkeel:0.3.0 # EDIT HERE: Replace the image name
          imagePullPolicy: Always
          command:
            - "python"
          args:
            - "/app/hello-tkeel.py"
          ports:
            - containerPort: 8080
          env:
            - name: KEEL_PRIVATE_STORE
              value: "0"